USE [master]
GO

/****** Object:  Database [NLDTK22CNT3lession07]    Script Date: 12/06/2024 11:09:30 SA ******/
CREATE DATABASE [NLDTK22CNT3lession07]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NLDTK22CNT3lession07', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER01\MSSQL\DATA\NLDTK22CNT3lession07.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NLDTK22CNT3lession07_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER01\MSSQL\DATA\NLDTK22CNT3lession07_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NLDTK22CNT3lession07].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET ARITHABORT OFF 
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET RECOVERY FULL 
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET  MULTI_USER 
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET QUERY_STORE = ON
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [NLDTK22CNT3lession07] SET  READ_WRITE 
GO

