//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLDTbaikiemtragiuaki.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NLDTSinhVien
    {
        public string NLDTMaSV { get; set; }
        public string NLDTHoSV { get; set; }
        public string NLDTTenSV { get; set; }
        public Nullable<System.DateTime> NLDTNgaySInh { get; set; }
        public Nullable<bool> NLDTPhai { get; set; }
        public string NLDTPhone { get; set; }
        public string NLDTEmail { get; set; }
        public string NLDTMaKH { get; set; }
    
        public virtual NLDTKhoa NLDTKhoa { get; set; }
    }
}
